{% set name = "csdms-cmip" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/cmip
  git_rev: v{{ version }}

build:
  string: py27_0

requirements:
  build:
    - babelizer
    - cmip
  run:
    - cca-tools
    - cmip

test:
  requires:
    - pymt

about:
  home: https://csdms.colorado.edu/wiki/Model:CMIP
  license: MIT
  summary: 
    The CMIP component provides access to a set of temperature and
    precipitation data in the permafrost regions of the world for
    years 1900 to 2100 from forecasts from CMIP models.
  dev_url: https://github.com/permamodel/cmip
